spring:
  jpa:
    show-sql: false

logging:
  level:
    edu.stanford.fsi.reap: INFO
  config: classpath:logback-prod.xml

application:
  secret-key: 9ECA9BE9-A8FE-44AD-B257-9ABF7622879F
  token-validity-day: 30
  map:
    key: 111