ALTER TABLE baby ADD COLUMN longitude DECIMAL(10,6) NULL COMMENT '经度';
ALTER TABLE baby ADD COLUMN latitude DECIMAL(10,6) NULL COMMENT '纬度';
ALTER TABLE baby ADD COLUMN show_location BIT(1) NULL COMMENT '是否展示经纬度，系统计算的经纬度默认不显示';
ALTER TABLE visit ADD COLUMN distance DECIMAL(20,6) NULL COMMENT '距离目的地距离';
